spring.application.name=log-ingestion-service
server.port=8080

# =====================================================
# KAFKA
# =====================================================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# =====================================================
# ACTUATOR
# =====================================================
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always

# =====================================================
# LOGGING
# =====================================================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.apache.kafka=INFO
logging.level.com.sahil=DEBUG